---
slurm_cluster_name: 'hyperchicken'
slurm_cluster_domain: ''
stack_prefix: 'hc'
mailhub: '192.168.0.5'
rewrite_domain: "{{ stack_prefix }}-sai{% if slurm_cluster_domain | length %}.{{ slurm_cluster_domain }}{% endif %}"
motd: "To solve or not to solve, that's the question."
vcompute_hostnames: "{{ stack_prefix }}-vcompute01"
vcompute_sockets: 16
vcompute_cores_per_socket: 1
vcompute_real_memory: 64264
vcompute_max_cpus_per_node: "{{ vcompute_sockets * vcompute_cores_per_socket - 2 }}"
vcompute_max_mem_per_node: "{{ vcompute_real_memory - vcompute_sockets * vcompute_cores_per_socket * 512 }}"
vcompute_local_disk: 0
vcompute_features: 'tmp09'
vcompute_ethernet_interfaces:
  - 'eth0'
  - 'eth1'
ui_hostnames: "{{ slurm_cluster_name }}"
ui_sockets: 4
ui_cores_per_socket: 1
ui_real_memory: 7821
ui_local_disk: 0
ui_features: 'prm09,tmp09'
ui_ethernet_interfaces:
  - 'eth0'
  - 'eth1'
ssh_host_signer_ca_private_key: "{{ ssh_host_signer_ca_keypair_dir }}/umcg-hpc-development-ca"
use_ldap: yes
uri_ldap: hc-dai
uri_ldaps: hc-dai
ldap_port: 389
ldaps_port: 636
ldap_base: ou=users,dc=hpc,dc=rug,dc=nl
ldap_binddn: cn=admin,ou=users,dc=hpc,dc=rug,dc=nl
ldap_domain: hpc.rug.nl
key_name: Gerben
image_cirros: cirros-0.3.4-x86_64-disk.img
image_centos7: centos7
cloud_user: centos
flavor_ui: s1.large
flavor_vcompute: s1.gargantuan
flavor_management: s1.small
public_net_id: ext-net-37
public_ip_addresses:
  portal: '193.62.55.164'
private_net_id: Solve-RD_private
private_subnet_id: Solve-RD_subnet
private_storage_net_id: net_provider_vlan3126
private_storage_subnet_id: subnet3126
security_group_id: SSH-and-ping-2
slurm_ldap: true
availability_zone: AZ_1
storage_availability_zone: nova
local_volume_size: 1
nameservers: [
  '/em-isi-3126.ebi.ac.uk/10.35.126.201',  # Local DNS lookups for shared storage.
  '8.8.4.4',  # Google DNS.
  '8.8.8.8',  # Google DNS.
]
local_admin_groups:
  - 'admin'
  - 'docker'
  - 'solve-rd'
  - 'umcg-atd'
  - 'depad'
local_admin_users:
  - 'centos'
  - 'egon'
  - 'gerben'
  - 'henkjan'
  - 'marieke'
  - 'morris'
  - 'pieter'
  - 'wim'
  - 'umcg-atd-dm'
  - 'solve-rd-dm'
  - 'envsync'
envsync_user: 'envsync'
envsync_group: 'depad'
hpc_env_prefix: '/apps'
local_regular_groups:
  - 'users'
  - 'depad'
  - 'solve-rd'
  - 'umcg-atd'
local_regular_users:
  - user: 'envsync'
    groups: ['depad']
  - user: 'solve-rd-dm'
    groups: ['solve-rd']
    sudoers: ['%solve-rd']
  - user: 'umcg-atd-dm'
    groups: ['umcg-atd']
    sudoers: ['%umcg-atd']
  - user: 'gvdvries'
    groups: ['users', 'depad', 'umcg-atd', 'solve-rd']
  - user: 'mbijlsma'
    groups: ['users', 'depad', 'umcg-atd', 'solve-rd']
  - user: 'mswertz'
    groups: ['users', 'depad', 'umcg-atd', 'solve-rd']
  - user: 'pneerincx'
    groups: ['users', 'depad', 'umcg-atd', 'solve-rd']
  - user: 'rkanninga'
    groups: ['users', 'depad', 'umcg-atd', 'solve-rd']
  - user: 'umcg-atd-dm'
    groups: ['users', 'umcg-atd']
    sudoers: ['pieter','gerben']
  - user: 'solve-rd-dm'
    groups: ['users', 'solve-rd']
    sudoers: ['%solve-rd']
pfs_mounts: [
  { pfs: 'ecst01',
    source: 'em-isi-3126.ebi.ac.uk:/ifs/Solve-RD/ecst01',
    type: 'nfs',
    rw_options: 'defaults,_netdev,noatime,nodiratime',
    ro_options: 'defaults,_netdev,noatime,nodiratime,ro' },
]
lfs_mounts: [
  { lfs: 'home',
    pfs: 'ecst01' },
  { lfs: 'groups/GROUP/tmp09',
    pfs: 'ecst01',
    groups: ['umcg-atd', 'solve-rd'] },
  { lfs: 'groups/GROUP/prm09',
    pfs: 'ecst01',
    groups: ['umcg-atd', 'solve-rd'] },
  { lfs: 'env09',
    pfs: 'ecst01',
    machines: "{{ groups['compute-vm'] + groups['user-interface'] }}" },
]
...
