$ANSIBLE_VAULT;1.1;AES256
39306430383937653465313262643266626162353565393265316337633637643134373437366234
3734316636626335343130383363353465343734633263620a313133616435333236373134343261
33656164373834656366303233626432623636316633303433346466386233393638373965653037
6636626264363763300a373237313163303565306230666362613163626135303365666439666531
35376632346633346662653036636364346564326539343233306661656633383036653632626337
30646337353962343831383937616362306533356663613237613761363632373461623964333636
63336234313564303563346264653366343561343139643631623935396364393136666665326637
36376135366237663834393565383062646465316435323538343965353635303031396264623430
36386233356138306133366338373166633737326332623939396235653436393362373133313065
38633966643466356531343233613566353932653463393134306361643131366465666639646635
63636537626533303530633766623466373064623237663764313434333834643431353439373538
33656335616162303462373636616264626136323532353833633639396431316132303135373632
35303264316538333961396334333465386338616230393433356534316137636130383631666239
65653434663862646262313462356362653139363339313436306461366565383735623364636538
35366530663933333432643161376665306538383432363132383831663732393263656433333866
30373963316634353265356332633863623563663836373365376366323338383539663731613062
32613537316136343539356264343137663537323962636534316161623161656262643563353164
30643634313235626363656233633534343863353631653437623639363233303439316339663838
33303664306532303130393138376431373861356635303532396562633766666332373231306435
37643534653334393862356532306534356531636339393533373937633966613261346637396431
32633937653565633963666239306633623435343138663063663562663530366161353435333039
63633462323635393162346235353739613735353934653131333432316666333331356630626432
31663863323331616432393763323137393831326337336236313731646462363835653631393331
61333631653463663633326664303637333631373339373762646631313465393436623135663535
33373335356637643861363865636362326434366165303562336465663333333963326238373839
3030646139323538616638383439376663353131353439346439
