---
slurm_cluster_name: 'gearshift'
slurm_cluster_domain: 'hpc.rug.nl'
stack_prefix: 'gs'
slurm_version: '18.08.8-1.el7.umcg'
mailhub: '172.23.34.34'
rewrite_domain: "imperator{% if slurm_cluster_domain | length %}.{{ slurm_cluster_domain }}{% endif %}"
motd: |
      !!! WARNING: This cluster is in beta testing
          and may be redeployed from scratch, which
          may result in complete data loss of home and tmp01 group folders
          starting on 09:00 on the following EOS Fridays:
          ###################################
          # Date                 EOS        #
          ###################################
          # Friday 2020-03-12    Sprint 152 #
          # Friday 2020-04-24    Sprint 154 #
          # Friday 2020-06-05    Sprint 156 #
          # Friday 2020-07-16    Sprint 158 #
          # Friday 2020-08-27    Sprint 160 #
          ###################################
          You have been warned!!!
          This does not affect prm03 group folders,
          which are on a different storage system.
additional_etc_hosts: |
  172.23.40.21       gs-compute01        gs-compute01.hpc.local
  172.23.40.22       gs-compute02        gs-compute02.hpc.local
  172.23.40.23       gs-compute03        gs-compute03.hpc.local
  172.23.40.24       gs-compute04        gs-compute04.hpc.local
  172.23.40.25       gs-compute05        gs-compute05.hpc.local
  172.23.40.26       gs-compute06        gs-compute06.hpc.local
  172.23.40.27       gs-compute07        gs-compute07.hpc.local
  172.23.40.28       gs-compute08        gs-compute08.hpc.local
  172.23.40.29       gs-compute09        gs-compute09.hpc.local
  172.23.40.30       gs-compute10        gs-compute10.hpc.local
  172.23.40.31       gs-compute11        gs-compute11.hpc.local
vcompute_hostnames: "{{ stack_prefix }}-vcompute[01-10]"
vcompute_sockets: 24
vcompute_cores_per_socket: 1
vcompute_real_memory: 221501
vcompute_max_cpus_per_node: "{{ vcompute_sockets * vcompute_cores_per_socket - 2 }}"
vcompute_max_mem_per_node: "{{ vcompute_real_memory - vcompute_sockets * vcompute_cores_per_socket * 512 }}"
vcompute_local_disk: 2800000
vcompute_features: 'tmp01'
vcompute_ethernet_interfaces:
  - 'eth0'
  - 'eth1'
  - 'eth2'
ui_hostnames: "{{ slurm_cluster_name }}"
ui_sockets: 24
ui_cores_per_socket: 1
ui_real_memory: 221501
ui_local_disk: 0
ui_features: 'prm03,tmp01'
ui_ethernet_interfaces:
  - 'eth0'
  - 'eth1'
ssh_host_signer_ca_private_key: "{{ ssh_host_signer_ca_keypair_dir }}/umcg-hpc-ca"
use_ldap: yes
create_ldap: no
uri_ldap: '172.23.40.249'
uri_ldaps: 'comanage-in.id.rug.nl'
ldap_port: '389'
ldaps_port: '636'
ldap_base: 'ou=research,o=asds'
ldap_binddn: 'cn=clusteradminumcg,o=asds'
ldap_group_object_class: 'groupofnames'
ldap_group_quota_soft_limit_template: 'ruggroupumcgquotaLFSsoft'
ldap_group_quota_hard_limit_template: 'ruggroupumcgquotaLFS'
filter_passwd: '(|(rugpersonentitlementvalue=scz)(rugpersonentitlementvalue=umcg))'
filter_shadow: '(|(rugpersonentitlementvalue=scz)(rugpersonentitlementvalue=umcg))'
pam_authz_search: '(|(&(objectClass=posixGroup)(cn=co_bbmri_g-GRP_Gearshift)(memberUid=$username))(&(cn=$username)(rugpersonentitlementvalue=umcg)))'
nameservers: [
  '172.23.40.244', # Order is important: local DNS for Isilon storage first!
  '8.8.4.4',       # Google DNS.
  '8.8.8.8',       # Google DNS.
]
local_admin_groups:
  - 'admin'
  - 'docker'
local_admin_users:
  - 'egon'
  - 'henkjan'
  - 'wim'
  - 'kees'
  - 'robin'
  - 'marlies'
envsync_user: 'umcg-envsync'
envsync_group: 'umcg-depad'
functional_admin_group: 'umcg-funad'
hpc_env_prefix: '/apps'
regular_groups:
  - 'umcg-aad'
  - 'umcg-as'
  - 'umcg-atd'
  - 'umcg-biogen'
  - 'umcg-bionic-mdd-gwama'
  - 'umcg-bios'
  - 'umcg-dag3'
  - 'umcg-datateam'
  - 'umcg-depad'
  - 'umcg-endocrinology'
  - 'umcg-franke-scrna'
  - 'umcg-gaf'
  - 'umcg-gap'
  - 'umcg-gastrocol'
  - 'umcg-gcc'
  - 'umcg-gdio'
  - 'umcg-gonl'
  - 'umcg-griac'
  - 'umcg-gsad'
  - 'umcg-impact'
  - 'umcg-lifelines'
  - 'umcg-lld'
  - 'umcg-llnext'
  - 'umcg-micompany'
  - 'umcg-mmbimg'
  - 'umcg-msb'
  - 'umcg-oncogenetics'
  - 'umcg-pub'
  - 'umcg-radicon'
  - 'umcg-solve-rd'
  - 'umcg-tifn'
  - 'umcg-ukb'
  - 'umcg-ugli'
  - 'umcg-verbeek'
  - 'umcg-weersma'
  - 'umcg-wijmenga'
regular_users:
  - user: 'umcg-aad-dm'
    groups: ['umcg-aad']
    sudoers: '%umcg-aad'
  - user: 'umcg-capicebot'
    groups: ['umcg-as']
    sudoers: '%umcg-as'
  - user: 'umcg-as-dm'
    groups: ['umcg-as']
    sudoers: '%umcg-as'
  - user: 'umcg-atd-ateambot'
    groups: ['umcg-atd']
    sudoers: '%umcg-atd'
  - user: 'umcg-atd-dm'
    groups: ['umcg-atd']
    sudoers: '%umcg-atd'
  - user: 'umcg-biogen-dm'
    groups: ['umcg-biogen']
    sudoers: 'umcg-hwestra,umcg-ndeklein'
  - user: 'umcg-bionic-mdd-gwama-dm'
    groups: ['umcg-bionic-mdd-gwama']
    sudoers: 'umcg-fhuider,umcg-ifedko'
  - user: 'umcg-bios-dm'
    groups: ['umcg-bios']
    sudoers: '%umcg-bios'
  - user: 'umcg-dag3-dm'
    groups: ['umcg-dag3']
    sudoers: 'umcg-avich,umcg-akurilshchikov,umcg-rgacesa'
  - user: 'umcg-datateam-dm'
    groups: ['umcg-datateam']
    sudoers: 'umcg-mbijlsma'
  - user: 'umcg-endocrinology-dm'
    groups: ['umcg-endocrinology']
    sudoers: '%umcg-endocrinology-dms'
  - user: 'umcg-franke-scrna-dm'
    groups: ['umcg-franke-scrna']
    sudoers: 'umcg-ddevries,umcg-hbrugge,umcg-mvdwijst'
  - user: 'umcg-gaf-ateambot'
    groups: ['umcg-gaf']
    sudoers: 'umcg-gvdvries,umcg-kdelange,umcg-mbenjamins,umcg-mbijlsma,umcg-pneerincx,umcg-rkanninga'
  - user: 'umcg-gaf-dm'
    groups: ['umcg-gaf']
    sudoers: 'umcg-gvdvries,umcg-kdelange,umcg-mbenjamins,umcg-mbijlsma,umcg-pneerincx,umcg-rkanninga'
  - user: 'umcg-gap-ateambot'
    groups: ['umcg-gap']
    sudoers: 'umcg-gvdvries,umcg-kdelange,umcg-mbenjamins,umcg-mbijlsma,umcg-pneerincx,umcg-rkanninga'
  - user: 'umcg-gap-dm'
    groups: ['umcg-gap']
    sudoers: 'umcg-gvdvries,umcg-kdelange,umcg-mbenjamins,umcg-mbijlsma,umcg-pneerincx,umcg-rkanninga'
  - user: 'umcg-gastrocol-dm'
    groups: ['umcg-gastrocol']
    sudoers: 'umcg-avich,umcg-hushixian'
  - user: 'umcg-gcc-dm'
    groups: ['umcg-gcc']
    sudoers: '%umcg-gcc'
  - user: 'umcg-gdio-dm'
    groups: ['umcg-gdio']
    sudoers: 'umcg-cvandiemen'
  - user: 'umcg-gonl-dm'
    groups: ['umcg-gonl']
    sudoers: 'umcg-pneerincx'
  - user: 'umcg-griac-dm'
    groups: ['umcg-griac']
    sudoers: 'umcg-cvermeulen,umcg-cxu,umcg-ndijk,umcg-mdevries,umcg-mberg'
  - user: 'umcg-gsad-dm'
    groups: ['umcg-gsad']
    sudoers: 'umcg-gvdvries,umcg-kdelange,umcg-mbenjamins,umcg-mbijlsma,umcg-pneerincx,umcg-rkanninga'
  - user: 'umcg-impact-dm'
    groups: ['umcg-impact']
    sudoers: '%umcg-impact'
  - user: 'umcg-lifelines-dm'
    groups: ['umcg-lifelines']
    sudoers: '%umcg-lifelines-dms'
  - user: 'umcg-lld-dm'
    groups: ['umcg-lld']
    sudoers: 'umcg-hwestra,umcg-hbrugge'
  - user: 'umcg-llnext-dm'
    groups: ['umcg-llnext']
    sudoers: 'umcg-tsinha,umcg-sgarmaeva'
  - user: 'umcg-micompany-dm'
    groups: ['umcg-micompany']
    sudoers: 'umcg-cxu,umcg-cvermeulen'
  - user: 'umcg-mmbimg-dm'
    groups: ['umcg-mmbimg']
    sudoers: '%umcg-mmbimg-dms'
  - user: 'umcg-msb-dm'
    groups: ['umcg-msb']
    sudoers: '%umcg-msb'
  - user: 'umcg-oncogenetics-dm'
    groups: ['umcg-oncogenetics']
    sudoers: '%umcg-mterpstra'
  - user: 'umcg-pub-dm'
    groups: ['umcg-pub']
    sudoers: 'umcg-pneerincx'
  - user: 'umcg-radicon-dm'
    groups: ['umcg-radicon']
    sudoers: 'umcg-gvdvries,umcg-kdelange,umcg-mbenjamins,umcg-mbijlsma,umcg-pneerincx,umcg-rkanninga'
  - user: 'umcg-solve-rd-dm'
    groups: ['umcg-solve-rd']
    sudoers: 'umcg-gvdvries,umcg-mbijlsma,umcg-pneerincx'
  - user: 'umcg-tifn-dm'
    groups: ['umcg-tifn']
    sudoers: 'umcg-akurilshchikov,umcg-jfu'
  - user: 'umcg-ukb-dm'
    groups: ['umcg-ukb']
    sudoers: '%umcg-ukb-dms'
  - user: 'umcg-ugli-dm'
    groups: ['umcg-ugli']
    sudoers: 'umcg-pdeelen,umcg-mbenjamins,umcg-pneerincx'
  - user: 'umcg-verbeek-dm'
    groups: ['umcg-verbeek']
    sudoers: '%umcg-verbeek'
  - user: 'umcg-weersma-dm'
    groups: ['umcg-weersma']
    sudoers: 'umcg-avich,umcg-hushixian'
  - user: 'umcg-wijmenga-dm'
    groups: ['umcg-wijmenga']
    sudoers: 'umcg-jgelderloos,umcg-aclaringbould,umcg-rmodderman,umcg-hwestra,umcg-avich,umcg-obakker,umcg-ddevries'
lustre_quota_type: 'group'
pfs_mounts: [
  { pfs: 'umcgst10',
    source: 'gcc-storage001.stor.hpc.local:/ifs/rekencluster',
    type: 'nfs4',
    rw_options: 'defaults,_netdev,vers=4.0,noatime,nodiratime',
    ro_options: 'defaults,_netdev,vers=4.0,noatime,nodiratime,ro' },
  { pfs: 'umcgst02',
    source: '172.23.57.203@tcp12:172.23.57.204@tcp12:/dh2',
    type: 'lustre',
    rw_options: 'defaults,lazystatfs,flock',
    ro_options: 'defaults,lazystatfs,ro' },
]
#
# Only anlysis team development (umcg-atd) group, which is exclusively used for testing has prm01 folder/mount for now.
#
lfs_mounts: [
  { lfs: 'home',
    pfs: 'umcgst10',
    machines: "{{ groups['cluster'] }}" },
  { lfs: 'tmp01',
    pfs: 'umcgst10',
    groups: [
        'umcg-aad', 'umcg-as', 'umcg-atd', 'umcg-biogen', 'umcg-bionic-mdd-gwama',
        'umcg-bios', 'umcg-dag3', 'umcg-datateam', 'umcg-endocrinology', 'umcg-franke-scrna',
        'umcg-gaf', 'umcg-gap', 'umcg-gastrocol', 'umcg-gcc', 'umcg-gdio', 'umcg-gonl',
        'umcg-griac', 'umcg-gsad', 'umcg-impact', 'umcg-lifelines', 'umcg-lld',
        'umcg-llnext', 'umcg-micompany', 'umcg-mmbimg', 'umcg-msb', 'umcg-oncogenetics',
        'umcg-pub', 'umcg-radicon', 'umcg-solve-rd', 'umcg-tifn', 'umcg-ukb', 'umcg-ugli',
        'umcg-verbeek', 'umcg-weersma', 'umcg-wijmenga'
      ]},
  { lfs: 'prm01',
    pfs: 'umcgst10',
    groups: [
        'umcg-atd'
      ]},
  { lfs: 'prm03',
    pfs: 'umcgst02',
    groups: [
        'umcg-aad', 'umcg-as', 'umcg-atd', 'umcg-biogen', 'umcg-bionic-mdd-gwama',
        'umcg-bios', 'umcg-dag3', 'umcg-datateam', 'umcg-endocrinology', 'umcg-franke-scrna',
        'umcg-gaf', 'umcg-gap', 'umcg-gastrocol', 'umcg-gcc', 'umcg-gdio', 'umcg-gonl',
        'umcg-griac', 'umcg-gsad', 'umcg-impact', 'umcg-lifelines', 'umcg-lld',
        'umcg-llnext', 'umcg-micompany', 'umcg-mmbimg', 'umcg-msb', 'umcg-oncogenetics',
        'umcg-pub', 'umcg-radicon', 'umcg-solve-rd', 'umcg-tifn', 'umcg-ukb', 'umcg-ugli',
        'umcg-verbeek', 'umcg-weersma', 'umcg-wijmenga'
      ]},
  { lfs: 'env01',
    pfs: 'umcgst10',
    machines: "{{ groups['compute-vm'] + groups['user-interface'] }}" },
]
...
