---
slurm_cluster_name: 'nibbler'
slurm_cluster_domain: 'hpc.rug.nl'
spacewalk_server_url: 'http://spacewalk02.hpc.rug.nl/XMLRPC'
stack_prefix: 'nb'
mailhub: '192.168.0.5'
rewrite_domain: "{{ stack_prefix }}-sai.{{ slurm_cluster_domain }}"
motd: "Besides, the determined Real Programmer can write FORTRAN programs in any language. -- Ed Post"
vcompute_hostnames: "{{ stack_prefix }}-vcompute[0-20]"
vcompute_sockets: 4
vcompute_cores_per_socket: 1
vcompute_real_memory: 3790
vcompute_max_cpus_per_node: "{{ vcompute_sockets * vcompute_cores_per_socket - 2 }}"
vcompute_max_mem_per_node: "{{ vcompute_real_memory - vcompute_sockets * vcompute_cores_per_socket * 512 }}"
vcompute_local_disk: 0
vcompute_features: 'tmp09'
vcompute_ethernet_interfaces:
  - 'eth0'
ui_hostnames: "{{ slurm_cluster_name }}"
ui_sockets: 4
ui_cores_per_socket: 1
ui_real_memory: 3790
ui_local_disk: 0
ui_features: 'prm09,tmp09'
ui_ethernet_interfaces:
  - 'eth0'
ssh_host_signer_ca_private_key: "{{ ssh_host_signer_ca_keypair_dir }}/umcg-hpc-development-ca"
use_ldap: yes
uri_ldap: ldap.pilot.scz.lab.surf.nl
uri_ldaps: ldap.pilot.scz.lab.surf.nl
ldap_port: 636
ldaps_port: 636
ldap_base: o=ElixirNL,dc=pilot-clients,dc=scz,dc=lab,dc=surf,dc=nl
ldap_binddn: cn=admin,o=ElixirNL,dc=pilot-clients,dc=scz,dc=lab,dc=surf,dc=nl
key_name: Fokke
image_cirros: cirros-0.3.4-x86_64-disk.img
image_centos7: centos7
cloud_user: centos
flavor_nano: s1.nano
flavor_tiny: s1.tiny
public_net_id: ext-net-37
private_net_id: internal_net
private_subnet_id: Solve-RD_subnet
private_storage_net_id: net_provider_vlan3126
private_storage_subnet_id: subnet3126
security_group_id: SSH-and-ping-2
slurm_ldap: true
availability_zone: AZ_1
local_volume_size: 1
nfs_network_range: 10.0.42.0/22
nfs_mountpoint: /nfs
nameservers: [
  '8.8.4.4',  # Google DNS.
  '8.8.8.8',  # Google DNS.
]
local_admin_groups:
  - 'admin'
  - 'docker'
local_admin_users:
  - 'egon'
  - 'gerben'
  - 'henkjan'
  - 'marieke'
  - 'morris'
  - 'fokke'
  - 'wim'
  - 'pieter'
  - 'wim'
  - 'umcg-atd-dm'
  - 'solve-rd-dm'
envsync_user: 'envsync'
envsync_group: 'depad'
hpc_env_prefix: '/apps'
local_regular_groups:
  - 'users'
  - 'depad'
  - 'solve-rd'
  - 'umcg-atd'
local_regular_users:
  - user: 'envsync'
    groups: ['depad']
  - user: 'gvdvries'
    groups: ['users', 'depad', 'umcg-atd', 'solve-rd']
  - user: 'mbijlsma'
    groups: ['users', 'depad', 'umcg-atd', 'solve-rd']
  - user: 'mswertz'
    groups: ['users', 'depad', 'umcg-atd', 'solve-rd']
  - user: 'pneerincx'
    groups: ['users', 'depad', 'umcg-atd', 'solve-rd']
  - user: 'rkanninga'
    groups: ['users', 'depad', 'umcg-atd', 'solve-rd']
  - user: 'umcg-atd-dm'
    groups: ['users', 'umcg-atd']
  - user: 'solve-rd-dm'
    groups: ['users', 'solve-rd']
pfs_mounts: [
  { pfs: 'Local-NFS',
    source: 'nb-nfs:/nfs',
    type: 'nfs4',
    rw_options: 'defaults,_netdev,vers=4.0,noatime,nodiratime',
    ro_options: 'defaults,_netdev,vers=4.0,noatime,nodiratime,ro' },
]
lfs_mounts: [
  { lfs: 'home',
    pfs: 'Local-NFS' },
  { lfs: 'groups/GROUP/tmp09',
    pfs: 'Local-NFS',
    groups: ['umcg-atd', 'solve-rd'] },
  { lfs: 'groups/GROUP/prm09',
    pfs: 'Local-NFS',
    groups: ['umcg-atd', 'solve-rd'] },
  { lfs: 'env09',
    pfs: 'Local-NFS',
    machines: "{{ groups['compute-vm'] + groups['user-interface'] }}" },
]
...
