---
ip_addresses:
  airlock:
    vlan983:
      address: 172.23.40.36
      netmask: /32
    vlan16:
      address: 129.125.60.196
      netmask: /32
      fqdn: 'airlock.hpc.rug.nl'
  gs-vcompute01:
    vlan983:
      address: 172.23.40.81
      netmask: /32
  gs-vcompute02:
    vlan983:
      address: 172.23.40.82
      netmask: /32
  gs-vcompute03:
    vlan983:
      address: 172.23.40.83
      netmask: /32
  gs-vcompute04:
    vlan983:
      address: 172.23.40.84
      netmask: /32
  gs-vcompute05:
    vlan983:
      address: 172.23.40.85
      netmask: /32
  gs-vcompute06:
    vlan983:
      address: 172.23.40.86
      netmask: /32
  gs-vcompute07:
    vlan983:
      address: 172.23.40.87
      netmask: /32
  gs-vcompute08:
    vlan983:
      address: 172.23.40.88
      netmask: /32
  gs-vcompute09:
    vlan983:
      address: 172.23.40.89
      netmask: /32
  gs-vcompute10:
    vlan983:
      address: 172.23.40.90
      netmask: /32
  gs-repo:
    vlan983:
      address: 172.23.40.98
      netmask: /32
  gearshift:
    vlan983:
      address: 172.23.40.33
      netmask: /32
    vlan985:
      address: 172.23.34.33
      netmask: /32
  imperator:
    vlan983:
      address: 172.23.40.34  # on shikra004
      #address: 172.23.40.31  # on shikra011
      netmask: /32
  sugarsnax:
    vlan983:
      address: 172.23.40.35
      netmask: /32
...
