---
slurm_cluster_name: 'gearshift'
stack_domain: 'hpc.rug.nl'
stack_name: "{{ slurm_cluster_name }}_cluster"  # stack_name must match the name of the folder that contains this vars.yml file.
stack_prefix: 'gs'
slurm_version: '22.05.2-1.el7.umcg'
slurm_partitions:
  - name: regular  # Must be in sync with group listed in Ansible inventory.
    default: yes
    nodes: "{{ stack_prefix }}-vcompute[01-10]"  # Must be in sync with Ansible hostnames listed in inventory.
    max_nodes_per_job: "{% if slurm_allow_jobs_to_span_nodes is defined and slurm_allow_jobs_to_span_nodes is true %}{{ groups['regular']|list|length }}{% else %}1{% endif %}"
    max_cores_per_node: "{{ groups['regular'] | map('extract', hostvars, 'slurm_max_cpus_per_node') | first }}"
    max_mem_per_node: "{{ groups['regular'] | map('extract', hostvars, 'slurm_max_mem_per_node') | first }}"
    local_disk: "{{ groups['regular'] | map('extract', hostvars, 'slurm_local_disk') | first | default(0, true) }}"
    features: "{{ groups['regular'] | map('extract', hostvars, 'slurm_features') | first | default('none') }}"
    extra_options: 'TRESBillingWeights="CPU=1.0,Mem=0.5G" DenyQos=ds-short,ds-medium,ds-long'
  - name: user_interface  # Must be in sync with group listed in Ansible inventory.
    default: no
    nodes: "{{ slurm_cluster_name }}"  # Must be in sync with Ansible hostnames listed in inventory.
    max_nodes_per_job: 1
    max_cores_per_node: 1
    max_mem_per_node: 1024
    local_disk: "{{ groups['user_interface'] | map('extract', hostvars, 'slurm_local_disk') | first | default(0, true) }}"
    features: "{{ groups['user_interface'] | map('extract', hostvars, 'slurm_features') | first | default('none') }}"
    extra_options: 'TRESBillingWeights="CPU=1.0,Mem=1.0G" AllowQos=ds-short,ds-medium,ds-long'
repo_manager: 'pulp'
figlet_font: 'cyberlarge'
motd: |
      ===============================================================
       Welcome to {{ slurm_cluster_name | capitalize }}
      ===============================================================
       WARNING: only prm* group dirs are backupped.
       When this cluster has to be redeployed from scratch,
       all data in home dirs and tmp* & rsc* group dirs will be lost!
      ===============================================================
additional_etc_hosts:
  - group: docs_library
    nodes:
      - name: docs_on_merlin
        network: vlan16
use_ldap: yes
create_ldap: no
use_sssd: yes
ldap_domains:
  idvault:
    uri: ldaps://172.23.40.249
    base: ou=umcg,o=asds
    schema: rfc2307
    min_id: 50100000
    max_id: 55999999
    user_object_class: posixAccount
    user_name: uid
    user_ssh_public_key: sshPublicKey
    user_member_of: groupMembership
    user_expiration_date: loginExpirationTime
    group_member: memberUid
    group_object_class: groupofnames
    #
    # LDAP is case insensitive, but we use lowercase only for quota field names,
    # so we can use simple literal strings in comparisons as opposed to regexes
    # to handle differences in UPPERCASE vs. lowercase.
    #
    # The UPPERCASE "LFS" in {{ ldap_domains[domain]['group_quota_*_limit_template'] }} Ansible variables
    # is a required placeholder that will get replaced with the value of the Logical File System (LFS)
    # for which we will try to fetch quota limits from the LDAP.
    # E.g. with
    #     group_quota_soft_limit_template: 'ruggroupumcgquotaLFSsoft'
    # the fieldname/key used to lookup the soft quota limit for the prm01 LFS is
    #     ruggroupumcgquotaprm01soft
    #
    group_quota_soft_limit_template: ruggroupumcgquotaLFSsoft
    group_quota_hard_limit_template: ruggroupumcgquotaLFS
stack_networks:
  - name: vlan983
    router_network: vlan16
    type: management
    external: true
  - name: vlan985
    type: storage
    external: true
nameservers: [
  '172.23.40.244', # Order is important: local DNS for Isilon storage first!
  '8.8.4.4',       # Google DNS.
  '8.8.8.8',       # Google DNS.
]
rsyslog_external_servers:
  - hostname: 172.23.47.250
    port: 514
nameserver_domain_overrides:
  - domain: hpc.local
    nameserver: 172.23.40.244
local_admin_groups:
  - 'admin'
  - 'docker'
local_admin_users:
  - 'bob'
  - 'egon'
  - 'fokke'
  - 'ger'
  - 'henkjan'
  - 'hopko'
  - 'kees'
  - 'marieke'
  - 'pieter'
  - 'robin'
  - 'sandi'
  - 'wim'
  - 'wouter'
data_transfer_only_group: umcg-sftp-only
envsync_user: 'umcg-envsync'
envsync_group: 'umcg-depad'
functional_admin_group: 'umcg-funad'
hpc_env_prefix: '/apps'
regular_groups:
  - "{{ data_transfer_only_group }}"
  - "{{ envsync_group }}"
  - "{{ functional_admin_group }}"
  - 'umcg-aad'
  - 'umcg-as'
  - 'umcg-atd'
  - 'umcg-biogen'
  - 'umcg-bionic-mdd-gwama'
  - 'umcg-bios'
  - 'umcg-cineca'
  - 'umcg-dag3'
  - 'umcg-datateam'
  - 'umcg-ejp-rd'
  - 'umcg-endocrinology'
  - 'umcg-fg'
  - 'umcg-franke-scrna'
  - 'umcg-fu'
  - 'umcg-gaf'
  - 'umcg-gap'
  - 'umcg-gastrocol'
  - 'umcg-gcc'
  - 'umcg-gdio'
  - 'umcg-gonl'
  - 'umcg-griac'
  - 'umcg-grip'
  - 'umcg-gsad'
  - 'umcg-hematology'
  - 'umcg-hlhs'
  - 'umcg-immunogenetics'
  - 'umcg-impact'
  - 'umcg-lifelines'
  - 'umcg-lld'
  - 'umcg-llnext'
  - 'umcg-mic'
  - 'umcg-micompany'
  - 'umcg-msb'
  - 'umcg-nawijn'
  - 'umcg-oncogenetics'
  - 'umcg-pmb'
  - 'umcg-pub'
  - 'umcg-radicon'
  - 'umcg-rehabilitation'
  - 'umcg-solve-rd'
  - 'umcg-sysops'
  - 'umcg-tifn'
  - 'umcg-ukb'
  - 'umcg-ugli'
  - 'umcg-verbeek'
  - 'umcg-vdakker'
  - 'umcg-weersma'
  - 'umcg-wijmenga'
regular_users:
  - user: "{{ envsync_user }}"
    groups: ["{{ envsync_group }}"]
  - user: 'umcg-aad-dm'
    groups: ['umcg-aad']
    sudoers: '%umcg-aad'
  - user: 'umcg-capicebot'
    groups: ['umcg-as']
    sudoers: '%umcg-as'
  - user: 'umcg-as-dm'
    groups: ['umcg-as']
    sudoers: '%umcg-as'
  - user: 'umcg-atd-ateambot'
    groups: ['umcg-atd']
    sudoers: '%umcg-atd'
  - user: 'umcg-atd-dm'
    groups: ['umcg-atd']
    sudoers: '%umcg-atd'
  - user: 'umcg-biogen-dm'
    groups: ['umcg-biogen']
    sudoers: '%umcg-biogen-dms'
  - user: 'umcg-bionic-mdd-gwama-dm'
    groups: ['umcg-bionic-mdd-gwama']
    sudoers: '%umcg-bionic-mdd-gwama-dms'
  - user: 'umcg-bios-dm'
    groups: ['umcg-bios']
    sudoers: '%umcg-bios'
  - user: 'umcg-cineca-dm'
    groups: ['umcg-cineca']
    sudoers: '%umcg-cineca-dms'
  - user: 'umcg-dag3-dm'
    groups: ['umcg-dag3']
    sudoers: '%umcg-dag3-dms'
  - user: 'umcg-datateam-dm'
    groups: ['umcg-datateam']
    sudoers: '%umcg-datateam'
  - user: 'umcg-ejp-rd-dm'
    groups: ['umcg-ejp-rd']
    sudoers: '%umcg-ejp-rd-dms'
  - user: 'umcg-endocrinology-dm'
    groups: ['umcg-endocrinology']
    sudoers: '%umcg-endocrinology-dms'
  - user: 'umcg-fg-dm'
    groups: ['umcg-fg']
    sudoers: '%umcg-fg-dms'
  - user: 'umcg-franke-scrna-dm'
    groups: ['umcg-franke-scrna']
    sudoers: '%umcg-franke-scrna-dms'
  - user: 'umcg-fu-dm'
    groups: ['umcg-fu']
    sudoers: '%umcg-fu-dms'
  - user: 'umcg-gaf-ateambot'
    groups: ['umcg-gaf']
    sudoers: 'umcg-gvdvries,umcg-kdelange,umcg-mbenjamins,umcg-mbijlsma,umcg-pneerincx,umcg-rkanninga'
  - user: 'umcg-gaf-dm'
    groups: ['umcg-gaf']
    sudoers: 'umcg-gvdvries,umcg-kdelange,umcg-mbenjamins,umcg-mbijlsma,umcg-pneerincx,umcg-rkanninga'
  - user: 'umcg-gap-ateambot'
    groups: ['umcg-gap']
    sudoers: 'umcg-gvdvries,umcg-kdelange,umcg-mbenjamins,umcg-mbijlsma,umcg-pneerincx,umcg-rkanninga'
  - user: 'umcg-gap-dm'
    groups: ['umcg-gap']
    sudoers: 'umcg-gvdvries,umcg-kdelange,umcg-mbenjamins,umcg-mbijlsma,umcg-pneerincx,umcg-rkanninga'
  - user: 'umcg-gastrocol-dm'
    groups: ['umcg-gastrocol']
    sudoers: '%umcg-gastrocol-dms'
  - user: 'umcg-gcc-dm'
    groups: ['umcg-gcc']
    sudoers: '%umcg-gcc'
  - user: 'umcg-gdio-dm'
    groups: ['umcg-gdio']
    sudoers: '%umcg-gdio-dms'
  - user: 'umcg-gonl-dm'
    groups: ['umcg-gonl']
    sudoers: '%umcg-gonl-dms'
  - user: 'umcg-griac-dm'
    groups: ['umcg-griac']
    sudoers: '%umcg-griac-dms'
  - user: 'umcg-grip-dm'
    groups: ['umcg-grip']
    sudoers: '%umcg-grip-dms'
  - user: 'umcg-gsad-dm'
    groups: ['umcg-gsad']
    sudoers: 'umcg-gvdvries,umcg-kdelange,umcg-mbenjamins,umcg-mbijlsma,umcg-pneerincx,umcg-rkanninga'
  - user: 'umcg-hematology-dm'
    groups: ['umcg-hematology']
    sudoers: '%umcg-hematology-dms'
  - user: 'umcg-hlhs-dm'
    groups: ['umcg-hlhs']
    sudoers: '%umcg-hlhs-dms'
  - user: 'umcg-immunogenetics-dm'
    groups: ['umcg-immunogenetics']
    sudoers: '%umcg-immunogenetics-dms'
  - user: 'umcg-impact-dm'
    groups: ['umcg-impact']
    sudoers: '%umcg-impact'
  - user: 'umcg-lifelines-dm'
    groups: ['umcg-lifelines']
    sudoers: '%umcg-lifelines-dms'
  - user: 'umcg-lld-dm'
    groups: ['umcg-lld']
    sudoers: '%umcg-lld-dms'
  - user: 'umcg-llnext-dm'
    groups: ['umcg-llnext']
    sudoers: '%umcg-llnext-dms'
  - user: 'umcg-mic-dm'
    groups: ['umcg-mic']
    sudoers: '%umcg-mic-dms'
  - user: 'umcg-micompany-dm'
    groups: ['umcg-micompany']
    sudoers: '%umcg-micompany-dms'
  - user: 'umcg-msb-dm'
    groups: ['umcg-msb']
    sudoers: '%umcg-msb'
  - user: 'umcg-nawijn-dm'
    groups: ['umcg-nawijn']
    sudoers: '%umcg-nawijn-dms'
  - user: 'umcg-oncogenetics-dm'
    groups: ['umcg-oncogenetics']
    sudoers: '%umcg-oncogenetics'
  - user: 'umcg-pmb-dm'
    groups: ['umcg-pmb']
    sudoers: '%umcg-pmb-dms'
  - user: 'umcg-pub-dm'
    groups: ['umcg-pub']
    sudoers: '%umcg-pub-dms'
  - user: 'umcg-radicon-dm'
    groups: ['umcg-radicon']
    sudoers: 'umcg-gvdvries,umcg-kdelange,umcg-mbenjamins,umcg-mbijlsma,umcg-pneerincx,umcg-rkanninga'
  - user: 'umcg-rehabilitation-dm'
    groups: ['umcg-rehabilitation']
    sudoers: '%umcg-rehabilitation-dms'
  - user: 'umcg-solve-rd-dm'
    groups: ['umcg-solve-rd']
    sudoers: '%umcg-solve-rd-dms'
  - user: 'umcg-sysops-dm'
    groups: ['umcg-sysops']
    sudoers: '%umcg-sysops'
  - user: 'umcg-tifn-dm'
    groups: ['umcg-tifn']
    sudoers: '%umcg-tifn-dms'
  - user: 'umcg-ukb-dm'
    groups: ['umcg-ukb']
    sudoers: '%umcg-ukb-dms'
  - user: 'umcg-ugli-dm'
    groups: ['umcg-ugli']
    sudoers: '%umcg-ugli-dms'
  - user: 'umcg-verbeek-dm'
    groups: ['umcg-verbeek']
    sudoers: '%umcg-verbeek'
  - user: 'umcg-vdakker-dm'
    groups: ['umcg-vdakker']
    sudoers: '%umcg-vdakker-dms'
  - user: 'umcg-weersma-dm'
    groups: ['umcg-weersma']
    sudoers: '%umcg-weersma-dms'
  - user: 'umcg-wijmenga-dm'
    groups: ['umcg-wijmenga']
    sudoers: '%umcg-wijmenga-dms'
#
# Shared storage related variables
#
lustre_client_networks:
   - name: tcp11
     interface: vlan985.lustre
   - name: tcp14
     interface: vlan985.lustre
pfs_mounts:
  - pfs: umcgst10
    source: 'gcc-storage001.stor.hpc.local:/ifs/rekencluster'
    type: nfs4
    rw_options: 'defaults,_netdev,vers=4.0,noatime,nodiratime'
    ro_options: 'defaults,_netdev,vers=4.0,noatime,nodiratime,ro'
    machines: "{{ groups['sys_admin_interface'] }}"
  - pfs: umcgst01
    source: '172.23.57.201@tcp11:172.23.57.202@tcp11:/dh1'
    type: lustre
    rw_options: 'defaults,_netdev,flock'
    ro_options: 'defaults,_netdev,ro'
    machines: "{{ groups['sys_admin_interface'] }}"
  - pfs: umcgst02
    source: '172.23.57.213@tcp14:172.23.57.214@tcp14:/umcg'
    type: lustre
    rw_options: 'defaults,_netdev,flock'
    ro_options: 'defaults,_netdev,ro'
    machines: "{{ groups['sys_admin_interface'] }}"
  - pfs: umcgst03
    source: '172.23.57.201@tcp11:172.23.57.202@tcp11:/dh1'
    type: lustre
    rw_options: 'defaults,_netdev,flock'
    ro_options: 'defaults,_netdev,ro'
    machines: "{{ groups['sys_admin_interface'] }}"
#
# Only anlysis team development (umcg-atd) group, which is exclusively used for testing has prm01 folder/mount for now.
#
lfs_mounts:
  - lfs: home
    pfs: umcgst10
    rw_machines: "{{ groups['cluster'] }}"
  - lfs: tmp01
    pfs: umcgst10
    groups:
      - name: umcg-aad
      - name: umcg-as
      - name: umcg-atd
      - name: umcg-biogen
      - name: umcg-bionic-mdd-gwama
      - name: umcg-bios
      - name: umcg-cineca
      - name: umcg-dag3
      - name: umcg-datateam
      - name: umcg-ejp-rd
      - name: umcg-endocrinology
      - name: umcg-franke-scrna
      - name: umcg-fg
        mode: '2750'
      - name: umcg-fu
      - name: umcg-gaf
      - name: umcg-gap
      - name: umcg-gastrocol
      - name: umcg-gcc
      - name: umcg-gdio
      - name: umcg-gonl
        mode: '2750'
      - name: umcg-griac
      - name: umcg-grip
        mode: '2750'
      - name: umcg-gsad
      - name: umcg-hematology
      - name: umcg-hlhs
        mode: '2750'
      - name: umcg-immunogenetics
      - name: umcg-impact
      - name: umcg-lifelines
        mode: '2750'
      - name: umcg-lld
      - name: umcg-llnext
      - name: umcg-mic
      - name: umcg-micompany
      - name: umcg-msb
      - name: umcg-nawijn
        mode: '2750'
      - name: umcg-oncogenetics
      - name: umcg-pmb
      - name: umcg-pub
        mode: '2750'
      - name: umcg-radicon
      - name: umcg-rehabilitation
      - name: umcg-solve-rd
      - name: umcg-sysops
      - name: umcg-tifn
      - name: umcg-ukb
        mode: '2750'
      - name: umcg-ugli
      - name: umcg-verbeek
      - name: umcg-vdakker
      - name: umcg-weersma
      - name: umcg-wijmenga
    rw_machines: "{{ groups['user_interface'] + groups['deploy_admin_interface'] + groups['compute_vm'] }}"
  - lfs: prm01
    pfs: umcgst10
    groups:
      - name: umcg-atd
    rw_machines: "{{ groups['user_interface'] }}"
  - lfs: prm02
    pfs: umcgst01
    quota_type: 'project'
    quota_pid_increment: 0  # Value added to GID to create unique PID for a group on the PFS hosting this LFS.
    groups:
      - name: umcg-aad
      - name: umcg-as
      - name: umcg-atd
      - name: umcg-biogen
      - name: umcg-bionic-mdd-gwama
      - name: umcg-bios
      - name: umcg-cineca
      - name: umcg-dag3
      - name: umcg-datateam
      - name: umcg-ejp-rd
      - name: umcg-endocrinology
      - name: umcg-franke-scrna
      - name: umcg-fg
      - name: umcg-fu
      - name: umcg-gaf
      - name: umcg-gap
      - name: umcg-gastrocol
      - name: umcg-gcc
      - name: umcg-gdio
      - name: umcg-gonl
      - name: umcg-griac
      - name: umcg-grip
      - name: umcg-gsad
      - name: umcg-hematology
      - name: umcg-hlhs
      - name: umcg-immunogenetics
      - name: umcg-impact
      - name: umcg-lifelines
      - name: umcg-lld
      - name: umcg-llnext
      - name: umcg-mic
      - name: umcg-micompany
      - name: umcg-msb
      - name: umcg-nawijn
      - name: umcg-oncogenetics
      - name: umcg-pmb
      - name: umcg-pub
      - name: umcg-radicon
      - name: umcg-rehabilitation
      - name: umcg-solve-rd
      - name: umcg-sysops
      - name: umcg-tifn
      - name: umcg-ukb
      - name: umcg-ugli
      - name: umcg-verbeek
      - name: umcg-vdakker
      - name: umcg-weersma
      - name: umcg-wijmenga
    rw_machines: "{{ groups['user_interface'] }}"
  - lfs: prm03
    pfs: umcgst02
    quota_type: 'project'
    quota_pid_increment: 200000  # Value added to GID to create unique PID for a group on the PFS hosting this LFS.
    groups:
      - name: umcg-aad
      - name: umcg-as
      - name: umcg-atd
      - name: umcg-biogen
      - name: umcg-bionic-mdd-gwama
      - name: umcg-bios
      - name: umcg-cineca
      - name: umcg-dag3
      - name: umcg-datateam
      - name: umcg-ejp-rd
      - name: umcg-endocrinology
      - name: umcg-franke-scrna
      - name: umcg-fg
      - name: umcg-fu
      - name: umcg-gaf
      - name: umcg-gap
      - name: umcg-gastrocol
      - name: umcg-gcc
      - name: umcg-gdio
      - name: umcg-gonl
      - name: umcg-griac
      - name: umcg-grip
      - name: umcg-gsad
      - name: umcg-hematology
      - name: umcg-hlhs
      - name: umcg-immunogenetics
      - name: umcg-impact
      - name: umcg-lifelines
      - name: umcg-lld
      - name: umcg-llnext
      - name: umcg-mic
      - name: umcg-micompany
      - name: umcg-msb
      - name: umcg-nawijn
      - name: umcg-oncogenetics
      - name: umcg-pmb
      - name: umcg-pub
      - name: umcg-radicon
      - name: umcg-rehabilitation
      - name: umcg-solve-rd
      - name: umcg-sysops
      - name: umcg-tifn
      - name: umcg-ukb
      - name: umcg-ugli
      - name: umcg-verbeek
      - name: umcg-vdakker
      - name: umcg-weersma
      - name: umcg-wijmenga
    rw_machines: "{{ groups['user_interface'] }}"
  - lfs: rsc01
    pfs: umcgst03
    quota_type: 'project'
    quota_pid_increment: 100000  # Value added to GID to create unique PID for a group on the PFS hosting this LFS.
    groups:
      - name: umcg-aad
      - name: umcg-as
      - name: umcg-atd
      - name: umcg-biogen
      - name: umcg-bionic-mdd-gwama
      - name: umcg-bios
      - name: umcg-cineca
      - name: umcg-dag3
      - name: umcg-datateam
      - name: umcg-ejp-rd
      - name: umcg-endocrinology
      - name: umcg-franke-scrna
      - name: umcg-fg
      - name: umcg-fu
      - name: umcg-gaf
      - name: umcg-gap
      - name: umcg-gastrocol
      - name: umcg-gcc
      - name: umcg-gdio
      - name: umcg-gonl
      - name: umcg-griac
      - name: umcg-grip
      - name: umcg-gsad
      - name: umcg-hematology
      - name: umcg-hlhs
      - name: umcg-immunogenetics
      - name: umcg-impact
      - name: umcg-lifelines
      - name: umcg-lld
      - name: umcg-llnext
      - name: umcg-mic
      - name: umcg-micompany
      - name: umcg-msb
      - name: umcg-nawijn
      - name: umcg-oncogenetics
      - name: umcg-pmb
      - name: umcg-pub
      - name: umcg-radicon
      - name: umcg-rehabilitation
      - name: umcg-solve-rd
      - name: umcg-sysops
      - name: umcg-tifn
      - name: umcg-ukb
      - name: umcg-ugli
      - name: umcg-verbeek
      - name: umcg-vdakker
      - name: umcg-weersma
      - name: umcg-wijmenga
    ro_machines: "{{ groups['compute_vm'] }}"
    rw_machines: "{{ groups['user_interface'] }}"
  - lfs: env01
    pfs: umcgst10
    ro_machines: "{{ groups['compute_vm'] + groups['user_interface'] }}"
    rw_machines: "{{ groups['deploy_admin_interface'] }}"
ega_fuse_client_mounts:
  cineca: '/groups/umcg-cineca/prm02/ega-fuse-client'
  solve_rd: '/groups/umcg-solve-rd/prm02/ega-fuse-client'
ega_fuse_client_java_home: '/etc/alternatives/jre_11_openjdk'
...
