---
- name: Install logrotate.
  ansible.builtin.package:
    state: 'latest'
    update_cache: true
    name: logrotate
  become: true

- name: Enable compression for old logs.
  ansible.builtin.lineinfile:
    path: /etc/logrotate.conf
    regexp: '^#?compress'
    line: 'compress'
    owner: root
    group: root
    mode: '0644'
  become: true
...
