---
- name: Find CA public key files
  ansible.builtin.find:
    paths: "{{ playbook_dir }}/ssh-host-ca/"
    patterns: "*.pub"
    follow: true
  register: ssh_ca_pub_files
  delegate_to: localhost
  connection: local

- name: Collect content from all the .pub files
  ansible.builtin.command: cat {{ item.path }}
  loop: "{{ ssh_ca_pub_files.files }}"
  loop_control:
    label: "{{ item.path | basename }}"
  register: ssh_ca_content
  changed_when: false
  delegate_to: localhost
  connection: local

- name: Make sure that /etc/ssh/ssh_known_hosts contains the .pub files
  ansible.builtin.lineinfile:
    regex: "^#?.*{{ item.stdout }}$"
    line: '@cert-authority * {{ item.stdout }}'
    path: /etc/ssh/ssh_known_hosts
    create: true
    mode: '0644'
  loop: "{{ ssh_ca_content.results }}"
  loop_control:
    label: "{{ item.item.path | basename }}"
  become: true

- name: Make sure /etc/ssh/ssh_config.d/*.conf config files are included.
  ansible.builtin.lineinfile:
    dest: /etc/ssh/ssh_config
    mode: '0644'
    owner: root
    group: root
    create: false
    insertafter: EOF
    regexp: "(?i)^#?Include /etc/ssh/ssh_config.d/.*$"
    line: 'Include /etc/ssh/ssh_config.d/*.conf'
  become: true

- name: 'Configure ssh client for external stack.'
  ansible.builtin.include_tasks:
    file: configure_ssh_client_for_external_stack.yml
  vars:
    external_stack: "{{ item }}"
  when:
    - ssh_client_configs is defined
    - inventory_hostname in groups['jumphost'] | default([]) or
      inventory_hostname in groups['cluster'] | default([])
  loop: "{{ ssh_client_configs }}"
...
