---
- name: 'Fetch the Lustre client source code.'
  get_url:
    url: 'https://downloads.whamcloud.com/public/lustre/lustre-2.11.0/el7.4.1708/client/SRPMS/lustre-client-dkms-2.11.0-1.el7.src.rpm'
    dest: '/tmp/lustre-client-dkms-2.11.0-1.el7.src.rpm'

- name: 'Build the Lustre client.'
  command:
    cmd: 'rpmbuild --rebuild --without servers /tmp/lustre-client-dkms-2.11.0-1.el7.src.rpm'
    creates: '/tmp/lustre-client-dkms-2.11.0-1.el7.src.rpm.rebuild'
...
