---
- name: Compile list of volumes to mount for NFS servers.
  ansible.builtin.set_fact:
    volumes: "{{ volumes | default([]) + [volume] }}"
  vars:
    volume:
      mount_point: "/mnt/{{ item['pfs'] }}"
      device: "{{ item['device'] }}"
      mounted_owner: root
      mounted_group: root
      mounted_mode: '0755'
      mount_options: 'rw,relatime'
      type: ext4
  when: inventory_hostname in groups['nfs_server'] | default([])
  with_items: "{{ pfs_mounts | selectattr('type', 'search', 'nfs') | selectattr('device', 'defined') | list }}"

- name: Check if volume source is a device.
  ansible.builtin.stat:
    path: "{{ item.device }}"
  register: mount_volume_device_stat
  loop: "{{ volumes }}"

- name: Create a file system on unformatted device.
  ansible.builtin.include_tasks:
    file: create_filesystem_on_device.yml
  vars:
    volume_mount_point: "{{ item.mount_point }}"
    volume_device: "{{ item.device }}"
    volume_type: "{{ item.type }}"
  when:
    - mount_volume_device_stat['results']
      | selectattr('item', 'equalto', item)
      | map(attribute='stat')
      | map(attribute='isblk')
      | first is true
  loop: "{{ volumes }}"

- name: Mount the volume.
  ansible.builtin.include_tasks:
    file: mount.yml
  vars:
    volume_path: "{{ item.mount_point }}"
    volume_src: "{{ item.device }}"
    volume_fstype: "{{ item.type }}"
    volume_opts: "{{ item.mount_options }}"
    volume_device: "{{ item.device }}"
  loop: "{{ volumes }}"

- name: Recheck the mount point.
  ansible.builtin.command: "mountpoint {{ item.mount_point }}"
  register: mount_point_status
  failed_when: false
  changed_when: false
  loop: "{{ volumes }}"

- name: Configure permissions for mounted file system.
  ansible.builtin.file:
    path: "{{ item.item.mount_point }}"
    state: directory
    owner: "{{ item.item.mounted_owner }}"
    group: "{{ item.item.mounted_group }}"
    mode: "{{ item.item.mounted_mode }}"
  when: item.rc == 0
  become: true
  loop: "{{ mount_point_status.results }}"

- name: Create sub folders on volumes.
  ansible.builtin.include_tasks:
    file: create_sub_folders.yml
  vars:
    mount_point: "{{ item.1.mount_point }}"
    folders: "{{ item.1.folders | list }}"
  when:
    - volume_folders is defined
    - item.0.mount_point == item.1.mount_point
    - inventory_hostname in item.1.machines
  loop: "{{ volumes | product(volume_folders) | list }}"
...
